spring:
  datasource:
    url: jdbc:mysql:/localhost:3306/accounts
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    sql:
      init:
        mode: always
    properties:
      hibernate:
        format_sql: true